foto/config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index'

  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'posts#index'

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
end

foto/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

foto/app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post

  validates :user_id, :notified_by_id, :post_id, :notice_type, presence: true
end

foto/app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, length: { minimum: 3, maximum: 300 }

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

foto/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :user_name, presence: true, length: { minimum: 4, maximum: 12 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_attached_file :avatar, styles: { medium: '152x152#' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

foto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

foto/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments.order('created_at asc')

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      create_notification @post, @comment
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = 'Check the comment form, something went wrong.'
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def create_notification(post, comment)
    return if post.user.id == current_user.id
    Notification.create(user_id: post.user.id,
                        notified_by_id: current_user.id,
                        post_id: post.id,
                        identifier: comment.id,
                        notice_type: 'comment')
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

foto/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    redirect_to post_path @notification.post
  end

  def index
    @notifications = current_user.notifications
  end
end

foto/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to root_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to root_path
    else
      flash[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Your post has been deleted."
    redirect_to root_path
  end

  def like
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

end

foto/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

end

foto/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

foto/app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    {
      success: 'alert-success text-center',
      error: 'alert-danger text-center',
      alert: 'alert-warning text-center',
      notice: 'alert-info text-center'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def form_image_select(post)
    return image_tag post.image.url(:medium),
                     id: 'image-preview',
                     class: 'img-responsive' if post.image.exists?
    image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
  end

  def profile_avatar_select(user)
    return image_tag user.avatar.url(:medium),
                     id: 'image-preview',
                     class: 'img-responsive img-circle profile-image' if user.avatar.exists?
    image_tag 'default-avatar.jpg', id: 'image-preview',
                                    class: 'img-responsive img-circle profile-image'
  end
end

foto/app/helpers/comments_helper.rb
module CommentsHelper
end

foto/app/helpers/notifications_helper.rb
module NotificationsHelper
end

foto/app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end
end

foto/app/helpers/profiles_helper.rb
module ProfilesHelper
end

foto/app/views/comments/_comment.html.haml
#comment
  .user-name
    = link_to comment.user.user_name, profile_path(comment.user.user_name)
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: {post_id: post.id, value: post.comments.count, confirm: "Are you sure?" }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do
      %span(class="glyphicon glyphicon-remove delete-comment-icon")

foto/app/views/comments/create.js.erb
$('#comment_content_<%= @post.id %>').val('')
$('#comment_content_<%= @post.id %>').blur();
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_count);

if (Append.comment || Append.open ){ $('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>"); }

else if ((Append.comment && Append.open) === false && Append.link === true) { 
	$('#comments_' + Append.post_id).append("<div class='paginator' id='#comments-paginator-" + Append.post_id + "'><a class='more-comments' id='more_comments_" + Append.post_id + "' data-post-id='" + Append.post_id + "' data-type='html' data-remote='true' data-value='" + Append.comment_count + "' href='/posts/" + Append.post_id + "/comments'>view all " + Append.comment_count + " comments</a></div>"); 
	ClickableCommentsLink(); 
}

else if ((Append.comment && Append.open && Append.link) === false) { $('#more_comments_<%= @post.id %>').html("view all <%= @post.comments.count %> comments"); }

foto/app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");
Append.comment_count -= 1

foto/app/views/comments/index.html.haml
= render @comments, post: @post

foto/app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        = link_to "Fotov", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = render 'notifications/notification_dropdown'
          %li
            = link_to "New Post", new_post_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

foto/app/views/layouts/application.html.haml
%html
  %head
    %title Fotov
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

%body
  = render 'layouts/navbar'
  -flash.each do |name, msg|
    .container
    = content_tag :div, msg, class: [:alert, alert_for(name)]
  = yield

foto/app/views/notifications/_notification.html.haml
%li
  = link_to "#{notification.notified_by.user_name} has #{notification.notice_type}ed on your post", link_through_path(notification)

foto/app/views/notifications/_notification_dropdown.html.haml
.dropdown.notification-dropdown
  %button.btn.btn-default.dropdown-toggle{ type: 'button', id: 'dropdownMenu1', data: { toggle: 'dropdown' }, 'aria-haspopup': true, 'aria-expanded': true }
    = current_user.notifications.count
    %span.glyphicon.glyphicon-flag
  %ul.dropdown-menu{ 'aria-labelledby': 'dropdownMenu1' }
    %li.dropdown-header.text-center Notifications
    = render current_user.notifications.order('created_at DESC').last(5)
    %li.divider{ role: 'separator' }
    %li.text-center= link_to 'View All', notifications_path

foto/app/views/notifications/index.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %ul.notification-index-list
        = render @notifications

foto/app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

foto/app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes post

foto/app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        =link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
        =time_ago_in_words post.created_at
    .image.center-block
      =link_to (image_tag post.image.url(:medium), class:'img-responsive'),
                 post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            =link_to post.user.user_name, profile_path(post.user.user_name)
          =post.caption
          .comments{id: "comments_#{post.id}"}
            -if post.comments.any?
              = render post.comments.first(4), post: post
              -unless post.comments.count <= 4
                .paginator{id: "#comments-paginator-#{post.id}"}
                  =link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data: {post_id: "#{post.id}", type: "html", value: "#{post.comments.count}"}
    .comment-like-form.row
      .col-sm-1.like-button
        =link_to '', like_post_path(post.id), remote: true,
                                              id: "like_#{post.id}",
                                              class: "like glyphicon #{liked_post post}"
      .comment-form.col-sm-11
        =form_for([post, post.comments.build], remote: true) do |f|
          =f.text_field :content, placeholder: 'Add a comment...',
                                   class: "comment_content",
                                   id: "comment_content_#{post.id}",
                                   data: { post_id: "#{post.id}",
                                   value: "#{post.comments.count}" }
          =f.submit 'New Comment', class: 'comment-submit-button' # Hidden with CSS

foto/app/views/posts/_posts.html.haml
= render @posts

foto/app/views/posts/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "cancel", root_path

foto/app/views/posts/index.html.haml
#posts
  = render 'posts'

#paginator.text-center
  = link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more'

foto/app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render @posts)%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

foto/app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

foto/app/views/posts/new.html.haml
= render "form" 

foto/app/views/posts/show.html.haml
= render 'post', post: @post
.text-center.edit-links
  - if @post.user.id == current_user.id
    = link_to "Cancel", posts_path
    |
    = link_to "Edit Post", edit_post_path(@post)
  - else
    =link_to "Cancel", root_path

foto/app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle.avatar-image
                  = profile_avatar_select(@user)
                = f.input :avatar, label: false,
                                   input_html: { onChange: 'loadFile(event)' }
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.input :bio, label: false, input_html: { rows: 4 }
          .form-group.text-center
            = f.button :submit, 'Update Profile', class: 'btn btn-success'

foto/app/views/profiles/show.html.haml
.posts-wrapper
  .row.profile-header
    .col-md-6
      .img-circle
        = profile_avatar_select(@user)
    .col-md-6
      .user-name-and-follow
        %h3.profile-user-name
          = @user.user_name
        %span
          - if @user == current_user
            = link_to 'Edit Profile', edit_profile_path(@user.user_name),
                                      class: 'btn edit-button'
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.posts.count, 'post'


-@posts.each do |post|
  = render 'posts/post', post: post